### ISSUE TITLE
Python3 support?

### ISSUE THREAD

**Issue by jpaldis** [matan1008/armulator#1]
Your project looks very interesting and potentially valuable to me.  However I need to be Python3.  I tried to run 2to3 on armulator.  This didn't quite work, but maybe the remaining issues are pretty trivial.  If you are interested in doing this I would definitely like to know.

The issues I hit so far were (1) writing to a RAM object from a string, which seems to be because Py3 strings are not bbytes but unicode and (2) after hacking the above, I got an exception from bitarrray about not being able to convert a float to an int.  Doing 2to3 on bitarray failed (__nonzero__ is not defined).

Sorry this isn't very helpful - not much more than a statement of interest and enthusiasm for what you've done.  Unfortunately I don't have time to do more at the moment.

**Comment by matan1008** [comment]
Thanks for the compliments! I will do it as soon as possible 😄

**Comment by matan1008** [comment]
Hey @jpaldis,
I solved the issue in the branch  feature/python3-support.
I don't merge it yet since it fails in installing on windows 10 with python 3.7 for a reason I don't really know, but you can use it as a module (or help me fixing the problem).

Best regards!
